### ISSUE TITLE
Release code ?

### ISSUE THREAD

**Issue by Diego999** [ucla-scai/Topic-RNN#1]
Hi,

I'm reading related papers on TopicRNN and I was wondering if you've planned to finally release the code ?

Thanks

**Comment by juwood03** [comment]
Hello, I think we are waiting until the paper has been accepted to a
conference/journal.

**Comment by Diego999** [comment]
Hi, thank you for your answer. I thought it might be https://arxiv.org/pdf/1611.01702v2.pdf but I guess this is another model with the same name.

**Comment by juwood03** [comment]
That is a different work than what we have.

**Comment by Diego999** [comment]
Thank your for your answer. Is your paper publicly available in Arxiv ?

**Comment by juwood03** [comment]
Not currently, I am not sure if we will publish it there due to many
conferences requiring blind submissions. While the paper is in press I
think would be the earliest we could do it.

**Comment by Diego999** [comment]
Ok, thank your for your answer !
